// Usiario
GET http://localhost:3001/usuario HTTP/1.1
###
GET http://localhost:3001/usuario/1 HTTP/1.1

###
POST http://localhost:3001/usuario HTTP/1.1
content-type: application/json

{
    "nomeCompleto": "Tiago Batista",
    "cpf":"12332112321",
    "email": "asdfasd@adsfas.com",
    "telefone": "12312312312"
}
###
DELETE  http://localhost:3001/usuario/1 HTTP/1.1
content-type: application/json
